[package]
name = "rem"
version = "0.1.2"
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["parser-implementations"]
description = "Parser for the remind REM format"
license = "MIT"
repostiory = "https://github.com/antoyo/rem-rs"

[dependencies]
